Added multiple files options to `UseDefaultConfigs`
eShopWorld/devops pull request #43
Opened 2021-01-04 16:20 UTC by tmenezes

- Added an overload in order to allow client apps to fully control the filenames and their respective order to be added into configuration builder.

2021-01-04 16:31 UTC, tabman83 requested changes
you need to update package v number and release notes otherwise the package won't be published by the release pipeline

2021-01-04 16:43 UTC, goenning commented on src/Eshopworld.DevOps/Extensions/ConfigurationExtensions.cs
> +        public static IConfigurationBuilder UseDefaultConfigs(this IConfigurationBuilder builder, string[] appSettingsFiles)
I think the other UseDefaultConfigs should could this method to remove some of the duplication on AddEnvironmentVariables and AddCommandLine

2021-01-04 16:43 UTC, goenning commented on src/Eshopworld.DevOps/Extensions/ConfigurationExtensions.cs
> +        public static IConfigurationBuilder UseDefaultConfigs(this IConfigurationBuilder builder, string[] appSettingsFiles)
other than that, looks good to me

2021-01-04 18:24 UTC, ppiriz commented on src/Eshopworld.DevOps/Extensions/ConfigurationExtensions.cs
> +                builder.AddJsonFile(file, true);
will we need to compose and send all 4 json files name?
i.e. 
"appsettings.json"
"appsettings.{env}.json" 
"appsettings2.json"
"appsettings2.{env}.json"

or can we send two file names and the specific environment will be added as well? we expect to be json files as we are using AddJsonFile.
i.e.
"appsettings"
"appsettings2"
and will result in same as above in the order:
"appsettings.json"
"appsettings.{env}.json" 
"appsettings2.json"
"appsettings2.{env}.json"

2021-01-04 23:46 UTC, rmccabe24 commented on src/Eshopworld.DevOps/Extensions/ConfigurationExtensions.cs
> +                builder.AddJsonFile(file, true);
If it was me - I'd possibly keep it simple and just send the explicit names when using the overload :-)

2021-01-05 11:35 UTC, tmenezes commented on src/Eshopworld.DevOps/Extensions/ConfigurationExtensions.cs
> +        public static IConfigurationBuilder UseDefaultConfigs(this IConfigurationBuilder builder, string[] appSettingsFiles)
Just refactored the code

2021-01-05 12:02 UTC, tabman83 approved these changes

2021-01-05 15:39 UTC, merged